keys:
  - &hosts:
    - &luminum age1ws3dyg036d3sjtxvfwt006hpcn8gd85xtyzae8fv33dptl4dg4dsmafsvl
  - &users:
    - &shringe age1fg0x99x8f0uxvtswget0alvk4g59tqx28vffke24l0hct45vgdwqgwe7wy
creation_rules:
  - path_regex: nixos/secrets.yaml$
    key_groups:
    - age:
      - *luminum
      - *shringe
  - path_regex: home-manager/homeManagerModules/secrets.yaml
    key_groups:
    - age:
      - *shringe

  
  # - path_regex: secrets.yaml$
  #   key_groups:
  #   - age:
  #     - *shringe
