{
  imports = [
    ./libreoffice.nix
    ./zanthura.nix
    ./gimp.nix
    ./joplin.nix
    ./feh.nix
    ./telegram.nix
    ./xournal.nix
    ./qtCaltulate.nix
    ./extraGtk.nix
    ./extraQt.nix
    ./bitwarden.nix
    ./llm.nix
    ./systemMonitor.nix
    ./weather.nix
    ./mpv.nix
  ];
}
