{
  imports = [
    ./waybar
    ./swaync.nix
    ./mpvpaper.nix
    ./cliphist.nix
    ./wofi.nix
    ./swaylock.nix
    ./scripts.nix
    ./hyprlock.nix
    ./swayosd.nix
    ./openrgb.nix
    ./dolphin.nix
    ./polkit.nix
    ./rot8.nix
    ./gammastep.nix
    ./systemd.nix
    ./swayidle.nix
    ./wlogout.nix
    ./swaybg.nix
    ./wluma.nix
    ./blueman.nix
  ];
}
