import = ["~/.config/alacritty/themes/themes/breeze.toml"]

[font.normal]
family = "MesloLGS NF"
style = "Regular"

[shell]
program = "fish"

[window]
opacity = 0.88

# [window.padding]
# x = 4
# y = 1

